name: dl_core_amap
description: An `Amap` Core Component, A Dart Bindings Generator For Native SDK.
version: 0.15.0
author: gavin <443403828@qq.com>
homepage: https://github.com/mature-road/dl_core_amap

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.13.0+1
  core_location_fluttify: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin